apiVersion: openfoundry.dev/v1alpha1
kind: Module
metadata:
  name: text-frequency
spec:
  entryPoint:
    command: [python3, main.py]
  environment:
    dependencyLock: requirements.lock
    dependencyDigest: sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
