apiVersion: openfoundry.dev/v1alpha1
kind: EvaluationSpec
metadata:
  name: example-affine
spec:
  metrics:
    - name: training-loss
      output: train.loss
      maximum: 0.000001
    - name: parameter-check
      output: evaluate.passed
      minimum: 1.0
